### ISSUE TITLE
Minor issues converting code to 2.0.0 

### ISSUE THREAD

**Issue by abailly-iohk** [input-output-hk/quickcheck-dynamic#29]
## RunModel

I am having some minor troubles converting Hydra to q-d 2.0.0 with the change from a handle-based `RunModel` to a typeclass based. 

I have this declaration
```
instance
  ( MonadDelay m
  , MonadAsync m
  , MonadCatch m
  , MonadTimer m
  , MonadThrow (STM m)
  , MonadLabelledSTM m
  ) =>
  RunModel WorldState (StateT (Nodes m) m)
  where
  postcondition _st (Commit _party expectedCommitted) _ actualCommitted = 
    pure $ expectedCommitted == actualCommitted
  postcondition _ _ _ _ = pure True
...
```

which looks fine but unfortunately does not compile because of:

```
test/Hydra/Model.hs:333:33: error:
    • Could not deduce: Realized
                          (StateT (Nodes m) m) [(CardanoSigningKey, Value)]
                        ~ [(CardanoSigningKey, Value)]
      from the context: a ~ UTxOType Payment
        bound by a pattern with constructor:
                   Commit :: Party
                             -> UTxOType Payment -> Action WorldState ActualCommitted,
                 in an equation for ‘postcondition’
        at test/Hydra/Model.hs:332:22-52
      Expected type: [(CardanoSigningKey, Value)]
        Actual type: Realized (StateT (Nodes m) m) a
    • In the second argument of ‘(==)’, namely ‘actualCommitted’
      In the second argument of ‘($)’, namely
        ‘expectedCommitted == actualCommitted’
      In the expression: pure $ expectedCommitted == actualCommitted
    • Relevant bindings include
        actualCommitted :: Realized (StateT (Nodes m) m) a
          (bound at test/Hydra/Model.hs:332:57)
        postcondition :: (WorldState, WorldState)
                         -> Action WorldState a
                         -> Test.QuickCheck.StateModel.LookUp (StateT (Nodes m) m)
                         -> Realized (StateT (Nodes m) m) a
                         -> StateT (Nodes m) m Bool
          (bound at test/Hydra/Model.hs:332:3)
    |
333 |     pure $ expectedCommitted == actualCommitted
    |                                 ^^^^^^^^^^^^^^^
```

`Realized` is a type family with an instance for `StateT s m` which says:

```
type instance Realized (State s m) a = Realized m a
```

which is annoying because I would like it to simply be 

```
type instance Realized (State s m) a = a
```

I could try to solve the issue by instantiating the `m` in the `RunModel` to be `IOSim s` but it does not work either. 

The only solution I found was to introduce a `newtype RunMonad m a = ...`. to wrap the `StateT` monad so that I can provide a custome instance of `Realized`. 

**Possible solution**: Remove the `type instance` declarations in the `StateModel` module?
 
## Redundant `Typeable a` constraint

When I declare my `nextAction` function:

```
  nextState :: WorldState -> Action WorldState a -> Var a -> WorldState
  nextState s@WorldState{hydraParties, hydraState} a _ =
```
I got the following errror:
```
test/Hydra/Model.hs:239:16: error: [-Wredundant-constraints, -Werror=redundant-constraints]
    • Redundant constraint: Typeable a
    • In the type signature for:
           nextState :: forall a.
                        Typeable a =>
                        WorldState -> Action WorldState a -> Var a -> WorldState
      When checking that instance signature for ‘nextState’
        is more general than its signature in the class
        Instance sig: forall a.
                      WorldState -> Action WorldState a -> Var a -> WorldState
           Class sig: forall a.
                      Typeable a =>
                      WorldState -> Action WorldState a -> Var a -> WorldState
      In the instance declaration for ‘StateModel WorldState’
    |
239 |   nextState :: WorldState -> Action WorldState a -> Var a -> WorldState
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
which I can ignore by switching the appropriate warning, but probably not something we want in general.

## Missing `Show` 

In declaring the `monitoring` function, 
```
  monitoring (s, s') action _l result = 
    decoratePostconditionFailure   . decorateTransitions
   where
    -- REVIEW: This should be part of the quickcheck-dynamic runActions
    decoratePostconditionFailure
      | checkOutcome s action result = id
      | otherwise =
        counterexample "postcondition failed"
          . counterexample ("Action: " <> show action)
          . counterexample ("State: " <> show s)
        .  counterexample ("Result: " <> show result)

    decorateTransitions =
      case (hydraState s, hydraState s') of
        (st, st') -> tabulate "Transitions" [unsafeConstructorName st <> " -> " <> unsafeConstructorName st']
```
I got 
```
test/Hydra/Model.hs:357:43: error:
    • Could not deduce (Show a) arising from a use of ‘show’
      from the context: (MonadAsync m, MonadCatch m, MonadTimer m,
                         MonadThrow (STM m), MonadLabelledSTM m)
        bound by the instance declaration
        at test/Hydra/Model.hs:(335,3)-(342,34)
      Possible fix:
        add (Show a) to the context of
          the type signature for:
            monitoring :: forall a.
                          (WorldState, WorldState)
                          -> Action WorldState a
                          -> Test.QuickCheck.StateModel.LookUp (RunMonad m)
                          -> Realized (RunMonad m) a
                          -> Test.QuickCheck.Property.Property
                          -> Test.QuickCheck.Property.Property
    • In the second argument of ‘(<>)’, namely ‘show result’
      In the first argument of ‘counterexample’, namely
        ‘("Result: " <> show result)’
      In the second argument of ‘(.)’, namely
        ‘counterexample ("Result: " <> show result)’
    |
357 |           . counterexample ("Result: " <> show result)
    |                                           ^^^^^^^^^^^
```
I can remove the `counterexample` but it's there for a reason.

**Comment by UlfNorell** [comment]
### RunModel
Did you try adding a `Realized m [(CardanoSigningKey, Value)] ~ [(CardanoSigningKey, Value)]` constraint to the instance head?

### Typeable constraint

That looks like a bug in ghc. I can reproduce on 8.10 with this program:
```haskell
{-# LANGUAGE InstanceSigs #-}
{-# OPTIONS_GHC -Wredundant-constraints #-}

class C a where
  foo :: Eq b => b -> a

instance C Int where
  foo :: b -> Int   -- With ghc < 9.0: Redundant constraint: Eq b
  foo _ = 0
```
With 9.0 and above I get no warning.

The constraint really isn't redundant; sometimes you do need the fact that `a` is `Typeable`, it's just that your particular instance doesn't. The workaround is to not use `InstanceSigs` on 8.10, or to disable the warning.

### Show constraint

This one is a little awkward. One trick I've used is to implement
```haskell
showFromAction :: Action Model a -> (Show a => b) -> b
showFromAction Action1{} k = k
...
```
and use that to bring the `Show` instance into scope. We should perhaps look into generating that function for you.

**Comment by abailly-iohk** [comment]
I tried `Realized m a ~ a`  which failed because `a` is not in scope. This error occurs several time with different types so I guess a specific instance like this one wouldn't help. The `newtype` wrapper solution works fine, but how about removing predefined instances in the `StateModel`?

**Comment by abailly-iohk** [comment]
re redundant `Typeable`: I am stupid, I should just have removed the type signature on `nextAction` and that's it

**Comment by abailly-iohk** [comment]
I tried `showFromAction` trick and it works well, thanks! I never thought of doing that 🤦

**Comment by MaximilianAlgehed** [comment]
> I tried `Realized m a ~ a` which failed because `a` is not in scope. This error occurs several time with different types so I guess a specific instance like this one wouldn't help. The `newtype` wrapper solution works fine, but how about removing predefined instances in the `StateModel`?

The thing I don't like about removing the predefined instance is that it's not uncommon that you have something like "ah crap I need some state / a reader component here" and for that situation it would be nice if you weren't forced to write down some awkward definition of `Realized` - especially if your target monad is e.g. `StateT MyRuntimeState IO` or something like that. As Ulf said I think the two fixes are either:
1. `newtype` but that's not the prettiest solution
2. adding constraints like `forall a. Realized m a ~ a` or maybe just a specific constraint in your case like `Realized m ModelTypeCausingError ~ TypeAtWhichIUseIt`?

**Comment by abailly-iohk** [comment]
> for that situation it would be nice if you weren't forced to write down some awkward definition of Realized
It does not feel that awkward, it's just a step one needs to take to define the `RunModel` and really just one line of code.
It seems to me we are inflicting our help on the implementor by providing _some_ instances and not others.

**Comment by MaximilianAlgehed** [comment]
I don't know that I agree with that. Now if you're using "normal" and concrete monads like `IO`, `IOSim`, `ReaderT`, `StateT`, most of the `Realized` machinery should be invisible (at least that's my goal) and only if you want to do something really fancy should it show up. I think that's still a worth-while goal to have no?

**Comment by abailly-iohk** [comment]
It won't be invisible most of the times, as it likely will pop up in errors anyway.

**Comment by MaximilianAlgehed** [comment]
@abailly-iohk how do you mean it will likely pop up in errors anyway? My intuition is that if people are writing instances that are monomorphic in the target monad (which I expect to be the "standard use case") then `Realized` should disappear. That's at least I think a reasonable design goal to avoid confusion. Doing what you're doing here is an "advanced technique" (that we should definitely document somewhere because it's super cool!) and then I'm totally fine with `Realized` showing up.

**Comment by MaximilianAlgehed** [comment]
Yes, I get what you mean. But my point is that you were having those issues because your code is polymorphic in the target monad :)

Yes, that sounds like a good idea.
