### ISSUE TITLE
`main` doesn't build on recent versions of GHC

### ISSUE THREAD

**Issue by MaximilianAlgehed** [input-output-hk/quickcheck-dynamic#32]
I tried building `main` on 9.0.2 and 9.2.4 and neither works... I suggest we maybe set up a GH action that builds with different versions of GHC? What do you think @abailly?

**Comment by abailly-iohk** [comment]
That's a good idea, I can give it a shot later today.

**Comment by MaximilianAlgehed** [comment]
I've fixed the issue (I think) but the formatter doesn't like the CPP pragma and ifdefs (we drop the formatter?) and we don't yet have the GH action. If you have the time @abailly-iohk to poke around with the build action that would be much appreciated.

**Comment by MaximilianAlgehed** [comment]
As far as Im aware - but I'm still on holiday so I can't check...

Den mån 14 aug. 2023 18:43Arnaud Bailly ***@***.***> skrev:
